name: Update Filtered M3U

on:
  schedule:
    # 每 6 小时运行一次: '0 */6 * * *'
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write  # 允许推送更改

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Filter and Update M3U Files
    permissions:
      contents: write # 需要写入权限来推送更改
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # ipaddress module is part of standard library in Python 3.3+
          pip install aiohttp # Only external dependency needed

      - name: Create default config file (if not present) with new structure
        run: |
          if [ ! -f config.json ]; then
            echo "config.json not found, creating default."
            # Use cat with EOF to create the multi-line JSON file
            cat << EOF > config.json
          {
              "global_settings": {
                  "request_timeout": 5,
                  "max_retries": 2,
                  "retry_delay": 2
              },
              "tasks": [
                  {
                      "name": "Merge & Filter V4/MyIPTV",
                      "enabled": true,
                      "urls": [
                          "https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u",
                          "https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv4.m3u"
                      ],
                      "processing_mode": "merge_filter",
                      "attributes_to_remove": ["tvg-logo", "tvg-id"],
                      "output_files": {
                          "https_output": "filtered_https_only.m3u",
                          "http_valid_output": "filtered_http_only_valid.m3u"
                      },
                      "filter_rules": {
                          "https_exclude_tvgname_contains": ["CGTN"]
                      }
                  },
                  {
                      "name": "Attribute Removal Global",
                      "enabled": true,
                      "urls": [
                          "https://raw.githubusercontent.com/YueChan/Live/refs/heads/main/Global.m3u"
                      ],
                      "processing_mode": "attributes_only",
                      "attributes_to_remove": ["tvg-logo", "tvg-id"],
                      "output_files": {
                          "processed_output": "filtered_global_attributes_removed.m3u"
                      }
                  }
              ]
          }
          EOF
          else
            echo "config.json found. Ensuring it's readable."
            # Basic validation - check if it's valid JSON (requires jq)
            # if command -v jq &> /dev/null; then
            #   if jq empty config.json > /dev/null 2>&1; then
            #      echo "config.json seems to be valid JSON."
            #   else
            #      echo "WARNING: config.json exists but is not valid JSON!" >&2
            #      # Decide whether to fail or continue with potentially broken config
            #   fi
            # else
            #    echo "jq not installed, skipping JSON validation."
            # fi
          fi
        shell: bash

      - name: Run M3U processing script
        run: python filter_m3u.py --config config.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto update filtered M3U files"
          # This pattern should catch all generated files based on the default config
          # Adjust if you change the output filenames significantly
          file_pattern: 'filtered_*.m3u'
          commit_options: '--signoff' # Optional: Add signoff to commits
